[font]
normal = { family = "Inconsolata", style = "Regular" }
bold = { family = "Inconsolata", style = "Regular" }
size = 18
[terminal.shell]
program = "/usr/bin/fish"
[window]
option_as_alt = "Both"
